export * from './college_controller'
export * from './course_controller'
export * from './faculty_controller'
export * from './lecture_controller'
export * from './student_controller'
export * from './super_admin_controller'
export * from './university_controller'